name: ${name}
description: ${description}
version: ${version}
authors: [${author}]
main: ${mainClass}
website: ${parent.url}
depend: [PlaceholderAPI, Skript]
softdepend: [Essentials, VanishNoPacket]

api-version: 1.13

commands:
  bestrpgstats:
    aliases: [rpgstats]
    usage: /<command>
    permission: lpgroupsync.command